src-git nas https://github.com/linkease/nas-packages.git;master
src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main
src-git istore https://github.com/linkease/istore.git;main
# src-git cups https://github.com/sirpdboy/luci-app-cupsd.git;main
src-git openclash https://github.com/vernesong/OpenClash.git;master
src-git helloworld https://github.com/fw876/helloworld.git;master
src-git openwrt_passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main
src-git openwrt_passwall https://github.com/xiaorouji/openwrt-passwall.git;main
src-git openwrt_passwall2 https://github.com/xiaorouji/openwrt-passwall2.git;main
